In [16]:
import csv
import numpy 
import pandas as pd

Ast = pd.read_csv('/home/gparreno/DataScience/Deep_Asteroid/Classification_Aten_Apollo Dataset.csv')
Ast.head(10)

      Emoid       Epoch     H      q      Q Class Discovery date
1   0.00586  2017/02/16  27.6  0.756  1.240  Aten     2017/02/27
2   0.01912  2017/02/16  27.3  0.810  1.066  Aten     2017/02/24
3   0.00051  2017/02/16  22.1  0.709  1.066  Aten     2017/02/23
4   0.16380  2017/02/16  22.2  0.375  1.245  Aten     2017/02/22
5   0.01142  2017/02/16  27.2  0.805  1.307  Aten     2017/02/22
6   0.01692  2017/02/16  26.8  0.314  1.050  Aten     2017/02/22
7   0.00162  2017/02/16  23.9  0.629  1.025  Aten     2017/02/15
8   0.05146  2017/02/16  25.9  0.942  1.054  Aten     2017/01/31
9   0.20297  2017/02/16  22.5  0.572  1.047  Aten     2017/01/31
10  0.04129  2017/02/16  24.9  0.853  1.210  Aten     2017/01/31
11  0.16589  2017/02/16  23.1  0.586  1.077  Aten     2017/01/31
12  0.00101  2017/02/16  27.3  0.633  1.377  Aten     2017/01/30
13  0.12030  2017/02/16  23.9  0.713  1.279  Aten     2017/01/28
14  0.00933  2017/02/16  25.2  0.794  1.142  Aten     2017/01/26
15  0.04862  2017/02/16  21.7  0.650  1.169  Aten     2017/01/26
16  0.00759  2017/02/16  27.9  0.742  1.223  Aten     2017/01/27
17  0.01019  2017/02/16  27.9  0.587  1.139  Aten     2017/01/26
18  0.01401  2017/02/16  26.1  0.678  1.177  Aten     2017/01/26
19  0.00929  2017/02/16  23.0  0.806  1.195  Aten     2017/01/22

In [7]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse
import sys
import tensorflow as tf

In [26]:
def main(_):
    #Import data 
    Ast = pd.read_csv('/home/gparreno/DataScience/Deep_Asteroid/Classification_Aten_Apollo Dataset.csv')
    
    #Create the model
    x = tf.placeholder(tf.float32, [None, 7])
    W = tf.Variable(tf.zeros([7, 2]))
    b = tf.Variable(tf.zeros([2]))
    y = tf.matmul(x,W) + b
    
    #Define loss and optimizer
    y_ = tf.placeholder(tf.float32, [None, 2])
    
    cross_entropy = tf.reduce_mean(
        tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))
    train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)
    
    sess = tf.InteractiveSession()
    tf.global_variables_initializer().run
    
    ## Train
    #for _ in range(100):
        #batch_xs, batch_ys = Ast[1:10]
        #sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})
        
    #Test trained model 
    correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.int32))
    print(sess.run(accuracy, feed_dict={x: Ast[1:20],
                                        y_: Ast[20:40]}))
    
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--data_dir', type=str, default='/tmp/tensorflow/Deep_Asteroid',
                        help='Directory for storing input data')
    FLAGS, unparsed = parser.parse_known_args()
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)

ValueError: invalid literal for float(): 2017/01/22